version: 2
models:
  - name: stg_orders
    columns:
      - name: order_id
        tests: [unique, not_null]
      - name: customer_id
        tests: [not_null]
      - name: currency
        tests:
          - accepted_values:
              values: ['EUR']
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [unique, not_null]
  - name: stg_events
    columns:
      - name: event_id
        tests: [unique, not_null]
